# TODO add
# def coalesce_duplicate_nodes(Node: Serial) -> Serial: ...


# def coalesce_duplicate_nodes(serial: Serial) -> SerialParallelDecomposition: ...


# def coalesce_duplicate_nodes(serial: Serial) -> SerialParallelDecomposition: ...


# def uncoalesce_duplicate_nodes(
#     g: SerialParallelDecomposition,
# ) -> SerialParallelDecomposition: ...

# def get_nodes_with_duplicates(g : DiGraph) -> MultiSet[Node]: ...
